<a href="https://colab.research.google.com/github/KunalAyush1/PyTorch_learning/blob/main/PyTorch1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
!nvidia-smi

Thu Jun 19 09:11:22 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
print(torch.cuda.is_available())

True


In [5]:
# Random Tensors
''' We can create tensors with random numbers..it is useful because the way many neural networks learn is that they start with tensors full of random numbers
and then adjust those random number to better suit the data'''

'''Start with random numbers -> Look at data -> update random numbers -> look at data -> update random numbers and so on'''

#creating

random_tnsor = torch.rand(2,4)
random_tnsor

tensor([[0.4862, 0.8133, 0.2945, 0.9282],
        [0.1189, 0.4494, 0.8003, 0.3281]])

In [6]:
random_tnsor.ndim

2

In [7]:
# creating a random tensor which is basically similar to image tensors
# image tensors have 3 dimesnsions colour channels(R,G,B),height and width
# So basically we can convert any image into numerical data using image tensors

random_image_tensor = torch.rand(size=(3,224,224))
random_image_tensor.shape, random_image_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [8]:
# creating a tensor consisting of 0 and 1

zero = torch.zeros(3,4)
ones = torch.ones(2,3)


In [9]:
#creating a tensors in a range

range_tensor = torch.arange(start=1,end = 1000, step = 18)
range_tensor


tensor([  1,  19,  37,  55,  73,  91, 109, 127, 145, 163, 181, 199, 217, 235,
        253, 271, 289, 307, 325, 343, 361, 379, 397, 415, 433, 451, 469, 487,
        505, 523, 541, 559, 577, 595, 613, 631, 649, 667, 685, 703, 721, 739,
        757, 775, 793, 811, 829, 847, 865, 883, 901, 919, 937, 955, 973, 991])

In [10]:
#*_like() functions in PyTorch create a new tensor with the same shape and data type as another tensor,
# but filled with a specific value or generated differently.


ones_like = torch.ones_like(input = range_tensor)
ones_like


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
#Tensor data types

''' This is one of the main issues in Pytorch or Deep Learning , we will be getting errors:
1) Tensors being not right data type
2) Tensors being not in right shape
3) Tensors being not on the right device(ie. if one tensor is on CPU and another one is on GPU(cuda) , and if we perform calculations on them , Pytorch will
throw an error)'''
#dtype means the data type we want to use, device means for which device we are creating tensores(cpu or gpu(cuda)), requires grad means if we want pytorch to
#keep track of gradients of the tensor
float_32_tensor = torch.tensor([3.0,6.0,7.8],dtype = None, device =None,requires_grad=False)

float_32_tensor.dtype
# by defaul data type of tensor is float32
# for more info visit pytorch docs

torch.float32

In [13]:
float_16_tensor = float_32_tensor.type(torch.float16)


In [15]:
float_32_tensor * float_16_tensor

''' Remember some operations will run error when we try to perform on different data types and some will not'''

' Remember some operations will run error when we try to perform on different data types and some will not'

In [22]:
# Getting information from a tensor
'''
1. data type of tensor => use tensor.dtype
2. shape of a tensor => use tensor.shape
3. dveice of tensor => use tensor.device

'''
tensor_1 = torch.rand(3,4)





In [23]:
print(f"Datatype of tensor : {tensor_1.dtype}")
print(f"Device of tensor : {tensor_1.device}")
print(f"Shape of tensor : {tensor_1.shape}")

Datatype of tensor : torch.float32
Device of tensor : cpu
Shape of tensor : torch.Size([3, 4])


In [28]:
# Manipulating Tensors(operations)

''' Tensor operations include :
1. Addition
2. Subtraction
3. Multiplication(element wise)
4. Division
5. Matrix multiplication'''

tensor_2 = torch.tensor([1,2,3])
tensor_3 = torch.tensor([1,2,3])

print(f"Addition of tensors : {tensor_2 + tensor_3}")
print(f"Subtraction of tensors : {tensor_2 - tensor_3}")
print(f"Multiplication(element-wise) of tensors : {tensor_2 * tensor_3}")
print(f"Division of tensors : {(tensor_2 / tensor_3).type(torch.int16)}")


Addition of tensors : tensor([2, 4, 6])
Subtraction of tensors : tensor([0, 0, 0])
Multiplication(element-wise) of tensors : tensor([1, 4, 9])
Division of tensors : tensor([1, 1, 1], dtype=torch.int16)


In [31]:
# Matrix Multiplication(dot product) we can use
'''
torch.matmul(tensor_1 , tensor_2)

or
tensor_1 @ tensor_@
'''



''' As tensor_2 and tensor_3 are simply vectors the matmul simply dot product them but as we go into higher dimensions;
there is a rule for matrix multiplication which is :
the inner dimension must match for matrix multiplication
and the resulting matrix has the shape of the outer dimensions

Example:
(2,3) and (3,4) is the shape of two matrix
 so 3 == 3 so it can be multiplied and the shape of the resulting matrix is (2,4)
'''

torch.matmul(tensor_2 , tensor_3)

tensor(14)

In [40]:
# Shape error in tensor multiplication in Deep Learning can be adjusted by taking transpose of one of the tensors
tensor_10 = torch.tensor([[1,2],
                         [3,4],
                         [6,7]])
tensor_11 = torch.tensor([[10,2],
                         [3,41],
                         [6,71]])
print(f'Shape of tensor_10 is {tensor_10.shape} and shape of tensor_11 is {tensor_11.shape}')
# so we need to take transpose of one of the tensors
tensor_10 @ tensor_11.T


Shape of tensor_10 is torch.Size([3, 2]) and shape of tensor_11 is torch.Size([3, 2])


tensor([[ 14,  85, 148],
        [ 38, 173, 302],
        [ 74, 305, 533]])