<a href="https://colab.research.google.com/github/KunalAyush1/PyTorch_learning/blob/main/PyTorch1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
#numpy array to tensors

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

In [5]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [6]:
'''
Note => The dault datatype of numpy array is float64 so while converting to tensor the tensor also becomes flaot64..to change we have to do type conversion

'''

tensor.type(torch.float16)

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float16)

In [7]:
tensor.dtype

torch.float64

In [12]:
#tensor to numpy
tensor_1 = torch.zeros(5)
numpy_tensor = tensor_1.numpy()

In [13]:
tensor_1.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [17]:
# Reproducibility(trying to take random out of random)(Reproducibility means getting the same results when running identical experiments)

''' In short how a neural network  works is:

start with random numbers -> tensor operations -> update random numbers to try to make them better representations of data->again->again....


To reduce the randommness in neural networks and PyTorch comes the concept of a random seed.

Essentially what the random seed does is "flavour" the randomness.

'''

random_1 = torch.rand(3,4)
random_2 = torch.rand(3,4)
print(random_1)
print(random_2)
# so there is a very little chance that both the tensors will be same or have some same elements
print(random_1 == random_2)

tensor([[0.4080, 0.8574, 0.6412, 0.4340],
        [0.0863, 0.3435, 0.7337, 0.3607],
        [0.1180, 0.3489, 0.0473, 0.1168]])
tensor([[0.9888, 0.0301, 0.3223, 0.8383],
        [0.6232, 0.4621, 0.4811, 0.7797],
        [0.2262, 0.0393, 0.0716, 0.4642]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [18]:
#Lets make some random but reproducible tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_3 = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_4 = torch.rand(3,4)
print(random_3)
print(random_4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


<h2>Running Tensors and PyTorch objects on the GPUs</h2>
*GPUs usage means faster computations thanks to CUDA + NVIDIA + PyTorch working behind the scenes to make everything good



<h3>Getting a GPU</h3>
1.Easiest is to use Google Colab for a free GPU<br>
2.Use your own GPU(takes investmet and steup)<br>
3.Use Cloud platforms like AWS , Azure ,etc to access GPUs on a rental basis


In [1]:
!nvidia-smi


Fri Jun 20 12:09:33 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [6]:
#check for GPU access

torch.cuda.is_available()

True

In [7]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [8]:
#Count no of GPU
torch.cuda.device_count()

1

In [11]:
# Putting tensors (and models) on the GPU

#Create a tensor on GPU , by default its on CPU..lets see
tensor = torch.rand(2,3)
tensor.device


device(type='cpu')

In [14]:
#Move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

In [15]:
# Note => If tensor is on GPU we cant tranform it to NumPy

#Moving back tensors to CPU
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [16]:
#To fix this we first need to move our tensor back to cpu to trasform it into NumPy

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([[0.2877196 , 0.9909075 , 0.9759872 ],
       [0.35043877, 0.778977  , 0.62320745]], dtype=float32)