<a href="https://colab.research.google.com/github/KunalAyush1/PyTorch_learning/blob/main/PyTorch1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [11]:
#Finding the min , max , Mean , sum, etc(Tensor Aggregation)
x = torch.arange(0,200,20)
x.dtype

torch.int64

In [7]:
print(torch.min(x))
# or
print(x.min())

tensor(0)
tensor(0)


In [8]:
print(torch.max(x))
# or
print(x.max())

tensor(180)
tensor(180)


In [12]:
'''Note => torch.mean() function requires a tensor of float32 data type to work'''
torch.mean(x.type(torch.float32))

tensor(90.)

In [13]:
# Finding the positional min and max
# which means the position at which minimum or maximum value is there

x.argmin()

tensor(0)

In [14]:
x.argmax()
# the argmin and argmax returns the index of min and max element in tensor respectively

tensor(9)

In [48]:

# Reshaping , stacking , squeezing and unsqueezing tensors

'''
Reshaping means changing the shape of the tensor but remember the shape must be compatible
'''
print(x.shape)
x_reshaped = x.reshape(10,1)
# shape of newly reshaped tensor = shape of original tensor
x_reshaped

torch.Size([10])


tensor([[  0],
        [ 20],
        [ 40],
        [ 60],
        [ 80],
        [100],
        [120],
        [140],
        [160],
        [180]])

In [20]:
''' view does the same job as reshape , it also reshapes a tensor
Note => .view() requires the tensor to be contiguous in memory.
'''

x.view(5,2)

tensor([[  0,  20],
        [ 40,  60],
        [ 80, 100],
        [120, 140],
        [160, 180]])

In [27]:
# Stacking is done with the help of torch.stack(-----, dim = ----)

x_stacked = torch.stack([x,x,x],dim = 1)

x_stacked

tensor([[  0,   0,   0],
        [ 20,  20,  20],
        [ 40,  40,  40],
        [ 60,  60,  60],
        [ 80,  80,  80],
        [100, 100, 100],
        [120, 120, 120],
        [140, 140, 140],
        [160, 160, 160],
        [180, 180, 180]])

In [34]:
# Squeezing
''' torch.squeeze() - removes all single dimensions from a target tensor(ie.It removes all dimensions of size 1 from a tensor’s shape.)
'''

y = torch.randn(1,5,2,1)
y_squeezed = torch.squeeze(y)
y_squeezed.shape

torch.Size([5, 2])

In [41]:
# Unsqueezing
'''torch.unsqueeze(tensor, dim) adds a dimension of size 1 at the specified dim (axis).

It doesn’t change the data — it just reshapes the tensor by adding a new dimension.
'''
y_unsqueezed = torch.unsqueeze(y_squeezed,dim = 0)

y_unsqueezed.shape

torch.Size([1, 5, 2])

In [47]:
#PERMUTING
'''
    torch.permute(*dims) reorders the dimensions of a tensor according to the specified order.

It's like rotating axes or rearranging the way data is viewed — without changing the data itself, only how it's accessed.'''

image = torch.randn(224,224,3)
image_permuted = image.permute(2,0,1) #dimension at second index will be now at zero index,simliarly.......
image_permuted.shape
# so it basically shuffles up the dimension as per our need and where do we want to put


torch.Size([3, 224, 224])

In [51]:
# Indexing ( selecting data from tensors)

z = torch.arange(1,10).reshape(1,3,3)
z,z.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [54]:
z[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
z[0][0]

tensor([1, 2, 3])

In [57]:
z[0][0][0]

tensor(1)

In [64]:
# index on z to return 9

z[0,2,2],  z[0][2][2]

(tensor(9), tensor(9))

In [62]:
# we use ":" to select all from a target dimension

z[0,2,2]

tensor(9)

In [65]:
# q. get all value of 0th and 1st dimenison but only index 1 of 2nd dimension

z[:,:,1]

tensor([[2, 5, 8]])

In [66]:
# q. Get all values of the 0 dimension but only 1 index value of 1st and 2nd dimenison
z[:,1,1]

tensor([5])