#### Using PyTorch's nn Module
* Its a core library that provides array of classes and functions which help developers to build neural networks efficiently and effectively.
* * `nn.Module` - base class for all neural network modules
* * common layers like `nn.Linear`, `nn.Conv2d`, `nn.LSTM`..
* * Activation functions like `nn.ReLU`, `nn.sigmoid`, `nn.Tanh`...
* * Loss functions such as `nn.CrossEntropyLoss`, `nn.MSELoss`, ..
* * Container modules like `nn.Sequential` to stack layers in order
** Regularization and Dropout like `nn.Dropout` and `nn.BatchNorm2d`..

In [44]:
import torch

In [45]:
print(torch.cuda.get_device_name())

NVIDIA A100-SXM4-40GB MIG 1g.5gb


In [46]:
import torch.nn as nn

In [47]:
class Model(nn.Module):
    
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [48]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.5838],
        [0.6213],
        [0.6291],
        [0.5566],
        [0.5930],
        [0.6114],
        [0.5854],
        [0.5860],
        [0.6800],
        [0.6503]], grad_fn=<SigmoidBackward0>)

In [49]:
model.linear.weight

Parameter containing:
tensor([[ 0.1275,  0.2830, -0.0039,  0.3704, -0.0068]], requires_grad=True)

In [50]:
!pip install torchinfo

In [51]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Making a more complex neural network
#### Architeture of the networks is as follows:
* No of `input_features` = 5(Layer1)
* No of `hidden layer` = 1 and no of `neurons per hidden layer` = 3(Layer2)
* No of `neurons` in output layer = 1(Layer3)

* Total number of trainable parameters = (5 * 3 + 3) + (1) =19 `( 15 weights and 4 bias)`
* Activation function used in hidden layer is `ReLU`
* Activation function used in ouput layer is `sigmoid`

In [56]:
class NN1(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        
        return out
        

In [58]:
model1 = NN1(features.shape[1])

In [59]:
model1(features)

tensor([[0.5895],
        [0.5759],
        [0.5633],
        [0.5756],
        [0.5689],
        [0.6056],
        [0.5672],
        [0.5903],
        [0.5750],
        [0.5778]], grad_fn=<SigmoidBackward0>)

In [ ]:
model1.linear1.weight # ( should have 15 wieghts)


Parameter containing:
tensor([[ 0.0851, -0.2736,  0.0877, -0.3805, -0.3797],
        [ 0.0026, -0.2062,  0.2187, -0.1386, -0.3834],
        [-0.4084, -0.2573,  0.1453,  0.0423,  0.1822]], requires_grad=True)

### Using sequential container
instead of using repetitive steps

In [64]:
class NN1(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    
    def forward(self, features):
        out = self.network(features)
        
        return out

In [65]:
model2 = NN1(features.shape[1])

In [66]:
model2(features)

tensor([[0.5317],
        [0.5172],
        [0.5199],
        [0.5265],
        [0.5325],
        [0.5290],
        [0.5239],
        [0.5413],
        [0.5314],
        [0.5236]], grad_fn=<SigmoidBackward0>)

## Now making a PyTorch pipeline using nn.Module 

In [67]:
import pandas as pd

In [69]:
df = pd.read_csv('https://github.com/prashant-kikani/breast-cancer-detection/raw/master/breast-cancer-data.csv')

In [70]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [71]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace=True)

In [72]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [73]:
df.shape

(569, 31)

In [77]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [78]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [83]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [84]:
X_train 

array([[ 0.38484095,  0.42421287,  0.44738522, ...,  1.49596902,
         0.18422888,  1.25074276],
       [ 0.18692193, -0.37060207,  0.15874406, ..., -0.49355807,
         1.18060544, -0.60971257],
       [ 1.02100922,  2.03940698,  1.03946966, ...,  1.24559882,
         0.13249074,  0.43260826],
       ...,
       [ 0.07665276,  0.11047013,  0.1649116 , ..., -0.20318971,
        -1.03578998,  0.27189287],
       [-0.53406878,  0.74027964, -0.5690264 , ..., -0.79476564,
         0.34611921, -0.07515921],
       [-0.09581953, -0.80519386, -0.06534346, ...,  0.3494567 ,
        -0.50672571,  1.14592838]])

In [85]:
X_test

array([[ 0.78083449, -0.14731311,  0.72733902, ...,  0.5433312 ,
        -0.17922356, -0.67474028],
       [ 0.47128004, -1.28733669,  0.42447519, ...,  0.39240579,
        -0.30573881, -0.74954888],
       [-1.3059097 , -0.82383635, -1.3093165 , ..., -0.59132601,
        -0.25629607, -0.22207679],
       ...,
       [-0.14204281,  0.56432379, -0.19120963, ..., -0.74723195,
        -0.70855174, -0.77194381],
       [-0.74957959, -1.13283658, -0.73760917, ..., -0.5597826 ,
         0.01127641,  0.25536407],
       [ 1.10774714,  0.3723691 ,  1.35381077, ...,  1.28286569,
         0.45335269,  1.58953015]])

In [87]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [101]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [102]:
X_train_tensor

tensor([[ 0.3848,  0.4242,  0.4474,  ...,  1.4960,  0.1842,  1.2507],
        [ 0.1869, -0.3706,  0.1587,  ..., -0.4936,  1.1806, -0.6097],
        [ 1.0210,  2.0394,  1.0395,  ...,  1.2456,  0.1325,  0.4326],
        ...,
        [ 0.0767,  0.1105,  0.1649,  ..., -0.2032, -1.0358,  0.2719],
        [-0.5341,  0.7403, -0.5690,  ..., -0.7948,  0.3461, -0.0752],
        [-0.0958, -0.8052, -0.0653,  ...,  0.3495, -0.5067,  1.1459]])

In [104]:
learning_rate = 0.1
epochs = 25
loss_fn = nn.BCELoss()

model = Model(X_train_tensor.shape[1])



for epoch in range(epochs):
    #forward pass
    y_pred = model(X_train_tensor)
    
    #loss calculation
    loss = loss_fn(y_pred, y_train_tensor.view(-1,1))
    
    loss.backward()
    
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad
    
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    
    
    print(f"Epoch: {epoch + 1} | Loss: {loss.item()}")
    

Epoch: 1 | Loss: 0.597266435623169
Epoch: 2 | Loss: 0.4778783321380615
Epoch: 3 | Loss: 0.41061773896217346
Epoch: 4 | Loss: 0.36661165952682495
Epoch: 5 | Loss: 0.3349114954471588
Epoch: 6 | Loss: 0.3106563985347748
Epoch: 7 | Loss: 0.2913198471069336
Epoch: 8 | Loss: 0.2754378020763397
Epoch: 9 | Loss: 0.26209360361099243
Epoch: 10 | Loss: 0.250679612159729
Epoch: 11 | Loss: 0.24077476561069489
Epoch: 12 | Loss: 0.23207645118236542
Epoch: 13 | Loss: 0.2243608683347702
Epoch: 14 | Loss: 0.2174583226442337
Epoch: 15 | Loss: 0.21123746037483215
Epoch: 16 | Loss: 0.20559486746788025
Epoch: 17 | Loss: 0.2004476636648178
Epoch: 18 | Loss: 0.19572873413562775
Epoch: 19 | Loss: 0.19138287007808685
Epoch: 20 | Loss: 0.187364399433136
Epoch: 21 | Loss: 0.1836349368095398
Epoch: 22 | Loss: 0.18016216158866882
Epoch: 23 | Loss: 0.17691850662231445
Epoch: 24 | Loss: 0.17388033866882324
Epoch: 25 | Loss: 0.1710273027420044


In [105]:
y_pred.shape

torch.Size([455, 1])

In [106]:
y_train_tensor.shape

torch.Size([455])

In [107]:
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = ( y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy}")

Accuracy: 0.5461680293083191


###Using PyTorch `torch.optim  `

In [110]:
learning_rate = 0.1
epochs = 25
loss_fn = nn.BCELoss()

model = Model(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr= learning_rate)



for epoch in range(epochs):
    #forward pass
    y_pred = model(X_train_tensor)
    
    #loss calculation
    loss = loss_fn(y_pred, y_train_tensor.view(-1,1))
    #clears gradient
    optimizer.zero_grad()
    #back prop
    loss.backward()
    #params update
    optimizer.step()
    
    
    
    print(f"Epoch: {epoch + 1} | Loss: {loss.item()}")
    

Epoch: 1 | Loss: 0.5763408541679382
Epoch: 2 | Loss: 0.48528024554252625
Epoch: 3 | Loss: 0.4268486201763153
Epoch: 4 | Loss: 0.38557761907577515
Epoch: 5 | Loss: 0.3545118272304535
Epoch: 6 | Loss: 0.3300641179084778
Epoch: 7 | Loss: 0.3101865351200104
Epoch: 8 | Loss: 0.2936185300350189
Epoch: 9 | Loss: 0.2795378565788269
Epoch: 10 | Loss: 0.2673827111721039
Epoch: 11 | Loss: 0.256754994392395
Epoch: 12 | Loss: 0.24736344814300537
Epoch: 13 | Loss: 0.23898962140083313
Epoch: 14 | Loss: 0.23146574199199677
Epoch: 15 | Loss: 0.22466056048870087
Epoch: 16 | Loss: 0.21846967935562134
Epoch: 17 | Loss: 0.21280866861343384
Epoch: 18 | Loss: 0.20760846138000488
Epoch: 19 | Loss: 0.20281198620796204
Epoch: 20 | Loss: 0.19837144017219543
Epoch: 21 | Loss: 0.19424642622470856
Epoch: 22 | Loss: 0.19040267169475555
Epoch: 23 | Loss: 0.18681079149246216
Epoch: 24 | Loss: 0.18344539403915405
Epoch: 25 | Loss: 0.1802845001220703


In [111]:
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = ( y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy}")

Accuracy: 0.5461680293083191
