<a href="https://colab.research.google.com/github/KunalAyush1/PyTorch_learning/blob/main/Pytorch1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To check whether you have a GPU active in Google Colab you can run:
!nvidia-smi

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch

And to see if PyTorch has access to the GPU, you can run:

import torch # Google Colab comes with torch already installed
print(torch.cuda.is_available()) # will return True if PyTorch can use the GPU


In [3]:

print(torch.cuda.is_available()) # will return True if PyTorch can use the GPU

False


In [5]:
#Introduction to Tensors

# Creating Tensors


# Scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [6]:
scalar.ndim

0

In [8]:
# Vector

vector = torch.tensor([10, 10])
vector

tensor([10, 10])

In [9]:
vector.ndim

1

In [10]:
vector.shape


torch.Size([2])

In [14]:
# MATRIX
MATRIX = torch.tensor([[ 1, 2],
                      [7, 8]])
MATRIX

tensor([[1, 2],
        [7, 8]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# TENSOR

TENSOR =  torch.tensor([[[1,2,3],
                         [3,4,5],
                         [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])